FROM node:slim

WORKDIR /backend

RUN apt-get update -y && apt-get install -y openssl

RUN npm install -g bun

COPY ./package.json .
RUN bun install

COPY ./prisma ./prisma
RUN bun run db:generate

COPY . .

EXPOSE 3000 5555

CMD ["bun", "run", "dev:docker"]