#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format:fix

# Backend build test
cd backend && npm run build && cd ..

# Frontend Build test
cd frontend && npm run build && cd ..

git add .